// src/content/pages/blog.ts
// All Family Health Care — Blog Hub & Pillar Pages Content

import type { SEOMeta } from "@/types/content";

// ─── BLOG HUB ─────────────────────────────────────────────────────────────────

export const blogSeo: SEOMeta = {
  title: "Home Health Care Blog | Guides for Patients & Caregivers",
  description:
    "Expert guides on home health care, Medicare benefits, caregiver support, and recovering at home — written by Chicago's trusted home health professionals.",
  keywords: [
    "home health care blog",
    "caregiver guides Chicago",
    "Medicare home health articles",
    "senior care resources Chicago",
  ],
  canonical: "https://www.allfamilyhealthcare.com/blog",
  ogImage: "/images/og/blog.jpg",
};

export const blogHero = {
  eyebrow: "Resources & Education",
  headline: "Guides Written for Real Families Making Hard Decisions",
  subheadline:
    "Whether you're trying to understand Medicare, care for a parent after a stroke, or prevent your mother from falling — our guides are written by clinicians, not copywriters.",
  note: "All content is written or reviewed by our licensed clinical team. We don't publish health information without a clinical lens.",
  image: {
    src: "/images/hero/blog.jpg",
    alt: "Healthcare clinician reviewing patient education materials on a tablet",
    width: 1344,
    height: 768,
  },
};

export const hubPages = [
  {
    slug: "senior-health",
    name: "Senior Health",
    icon: "heart",
    description: "Health guides for older adults and the families who care for them.",
    articleCount: 8,
  },
  {
    slug: "caregiver-support",
    name: "Caregiver Support",
    icon: "users",
    description: "Practical help for family members managing care for a loved one.",
    articleCount: 6,
  },
  {
    slug: "home-recovery",
    name: "Home Recovery",
    icon: "home",
    description: "Recovering from surgery, illness, or hospitalization at home.",
    articleCount: 6,
  },
  {
    slug: "chronic-conditions",
    name: "Chronic Conditions",
    icon: "activity",
    description: "Managing heart disease, COPD, diabetes, and other ongoing conditions.",
    articleCount: 6,
  },
  {
    slug: "home-safety",
    name: "Home Safety",
    icon: "shield-check",
    description: "Fall prevention, home modifications, and safety for seniors.",
    articleCount: 5,
  },
  {
    slug: "medicare-guides",
    name: "Medicare Guides",
    icon: "dollar-sign",
    description: "Understanding what Medicare covers — and how to access your benefits.",
    articleCount: 4,
  },
];

// ─── ALL BLOG ARTICLES METADATA ───────────────────────────────────────────────
// Used for blog index, hub pages, and related article widgets

export const allArticles = [
  // PILLAR PAGES
  {
    slug: "ultimate-guide-home-health-care",
    title: "The Complete Guide to Home Health Care",
    excerpt: "Everything Chicago families need to know — who qualifies, what Medicare covers, how to start, and what to expect.",
    category: "Getting Started",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-01-15",
    readTime: "14 min",
    isPillar: true,
    tags: ["home health care", "Medicare", "Chicago", "getting started"],
  },
  {
    slug: "medicare-home-health-benefits-explained",
    title: "What Medicare Actually Covers for Home Health Care",
    excerpt: "A clear, plain-language guide to Medicare home health benefits — what's covered, who qualifies, and how to use your benefits.",
    category: "Medicare Guides",
    cluster: "skilled-nursing",
    hub: "medicare-guides",
    publishDate: "2025-01-22",
    readTime: "10 min",
    isPillar: true,
    tags: ["Medicare", "home health benefits", "coverage", "Chicago"],
  },
  {
    slug: "family-caregiver-survival-guide",
    title: "The Family Caregiver Survival Guide",
    excerpt: "A comprehensive resource for adult children and spouses managing care for a loved one at home — covering everything from burnout to legal planning.",
    category: "Caregiver Support",
    cluster: "caregiver",
    hub: "caregiver-support",
    publishDate: "2025-02-01",
    readTime: "15 min",
    isPillar: true,
    tags: ["caregiver", "family", "burnout", "support"],
  },
  {
    slug: "aging-in-place-complete-guide",
    title: "Aging in Place: The Complete Guide for Chicago Families",
    excerpt: "How to help a parent or loved one safely remain in their home as they age — including home modifications, care resources, and planning ahead.",
    category: "Senior Health",
    cluster: "caregiver",
    hub: "senior-health",
    publishDate: "2025-02-15",
    readTime: "12 min",
    isPillar: true,
    tags: ["aging in place", "senior care", "Chicago", "home modifications"],
  },
  {
    slug: "recovering-from-surgery-at-home",
    title: "Recovering from Surgery at Home: What Every Patient Needs to Know",
    excerpt: "A guide for patients and families preparing for home recovery after surgery — what to expect, how to prepare, and how home health care helps.",
    category: "Home Recovery",
    cluster: "post-hospital",
    hub: "home-recovery",
    publishDate: "2025-03-01",
    readTime: "11 min",
    isPillar: true,
    tags: ["surgery recovery", "post-surgical care", "home health", "Chicago"],
  },
  {
    slug: "chronic-disease-management-at-home",
    title: "Managing Chronic Disease at Home: A Guide for Patients and Families",
    excerpt: "How to manage heart failure, COPD, diabetes, and other chronic conditions safely at home — with professional support from a home health team.",
    category: "Chronic Conditions",
    cluster: "chronic-disease",
    hub: "chronic-conditions",
    publishDate: "2025-03-15",
    readTime: "12 min",
    isPillar: true,
    tags: ["chronic disease", "heart failure", "COPD", "diabetes", "home health"],
  },
  {
    slug: "how-to-prevent-hospital-readmissions",
    title: "How to Prevent Hospital Readmissions After Discharge",
    excerpt: "Why readmissions happen, and the steps that dramatically reduce the risk — including the critical role of home health care.",
    category: "Home Recovery",
    cluster: "post-hospital",
    hub: "home-recovery",
    publishDate: "2025-04-01",
    readTime: "9 min",
    isPillar: true,
    tags: ["hospital readmission", "discharge planning", "home health care"],
  },
  {
    slug: "skilled-nursing-care-complete-guide",
    title: "Skilled Nursing Care at Home: The Complete Guide",
    excerpt: "What skilled nursing care is, who needs it, what nurses actually do in the home, and how to access it through Medicare.",
    category: "Getting Started",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-04-15",
    readTime: "10 min",
    isPillar: true,
    tags: ["skilled nursing", "home nurse", "Medicare nursing", "Chicago"],
  },

  // SKILLED NURSING CLUSTER
  {
    slug: "what-is-skilled-nursing-care",
    title: "What Is Skilled Nursing Care? (And Is It Different from Regular Home Care?)",
    excerpt: "Many people confuse skilled nursing with non-medical home care. Here's exactly what skilled nurses do — and why the difference matters.",
    category: "Getting Started",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-01-29",
    readTime: "6 min",
    isPillar: false,
    tags: ["skilled nursing", "home health", "nurse visits"],
  },
  {
    slug: "signs-you-need-skilled-nursing",
    title: "7 Signs Your Parent Needs Skilled Nursing Care at Home",
    excerpt: "Many families wait too long. Here are the warning signs that indicate it's time for a skilled nurse to visit your loved one at home.",
    category: "Getting Started",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-02-05",
    readTime: "5 min",
    isPillar: false,
    tags: ["skilled nursing", "warning signs", "caregiver", "senior care"],
  },
  {
    slug: "skilled-nursing-vs-home-care",
    title: "Skilled Nursing vs. Non-Medical Home Care: What's the Difference?",
    excerpt: "The difference between skilled nursing care and personal home care — and how to know which one your loved one actually needs.",
    category: "Getting Started",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-02-12",
    readTime: "5 min",
    isPillar: false,
    tags: ["skilled nursing", "home care", "difference", "Medicare"],
  },
  {
    slug: "how-nurses-manage-medications",
    title: "How Home Health Nurses Manage Medications for Seniors",
    excerpt: "Medication errors are one of the leading causes of senior hospitalizations. Here's how home health nurses prevent them.",
    category: "Senior Health",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-03-05",
    readTime: "6 min",
    isPillar: false,
    tags: ["medication management", "senior safety", "home health nurse"],
  },
  {
    slug: "wound-care-at-home-guide",
    title: "Wound Care at Home: What Patients and Caregivers Need to Know",
    excerpt: "A guide to managing wounds at home — when a wound needs skilled nursing care, what nurses do during wound care visits, and how to prevent infection.",
    category: "Senior Health",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-03-19",
    readTime: "7 min",
    isPillar: false,
    tags: ["wound care", "home nursing", "infection prevention", "diabetic wounds"],
  },
  {
    slug: "iv-therapy-at-home",
    title: "IV Therapy at Home: What It Is and Who Qualifies",
    excerpt: "IV antibiotics and infusion therapy can now be administered at home by skilled nurses — avoiding hospital stays and improving recovery.",
    category: "Senior Health",
    cluster: "skilled-nursing",
    hub: "senior-health",
    publishDate: "2025-04-09",
    readTime: "6 min",
    isPillar: false,
    tags: ["IV therapy", "home health", "skilled nursing", "Medicare"],
  },

  // CAREGIVER CLUSTER
  {
    slug: "how-to-care-for-aging-parents",
    title: "How to Care for Aging Parents at Home: A Practical Guide",
    excerpt: "A realistic, step-by-step guide for adult children managing the care of an aging parent — without losing their own health and sanity.",
    category: "Caregiver Support",
    cluster: "caregiver",
    hub: "caregiver-support",
    publishDate: "2025-02-08",
    readTime: "8 min",
    isPillar: false,
    tags: ["aging parents", "caregiver", "family care", "Chicago"],
  },
  {
    slug: "caregiver-burnout-warning-signs",
    title: "Caregiver Burnout: Warning Signs Every Family Needs to Recognize",
    excerpt: "Recognizing caregiver burnout before it becomes a crisis — and what to do when you recognize yourself in these signs.",
    category: "Caregiver Support",
    cluster: "caregiver",
    hub: "caregiver-support",
    publishDate: "2025-02-15",
    readTime: "7 min",
    isPillar: false,
    tags: ["caregiver burnout", "exhaustion", "family caregiver", "support"],
  },
  {
    slug: "how-to-balance-work-and-caregiving",
    title: "How to Balance Work and Caregiving (Without Sacrificing Either)",
    excerpt: "Practical strategies for working adult children managing a parent's care — from FMLA rights to professional home health support.",
    category: "Caregiver Support",
    cluster: "caregiver",
    hub: "caregiver-support",
    publishDate: "2025-02-22",
    readTime: "7 min",
    isPillar: false,
    tags: ["work-life balance", "caregiving", "FMLA", "adult child caregiver"],
  },
  {
    slug: "when-to-consider-home-health-care",
    title: "When Should You Consider Home Health Care for a Parent?",
    excerpt: "The specific situations and warning signs that indicate it's time to call a home health agency — and what happens next.",
    category: "Getting Started",
    cluster: "caregiver",
    hub: "caregiver-support",
    publishDate: "2025-03-01",
    readTime: "6 min",
    isPillar: false,
    tags: ["when to call", "home health decision", "caregiver", "senior care"],
  },
  {
    slug: "communication-with-elderly-parents",
    title: "How to Talk to Your Parents About Getting Help at Home",
    excerpt: "Many seniors resist home health care. Here's how to have the conversation in a way that preserves dignity and actually works.",
    category: "Caregiver Support",
    cluster: "caregiver",
    hub: "caregiver-support",
    publishDate: "2025-03-08",
    readTime: "7 min",
    isPillar: false,
    tags: ["elderly parents", "conversation", "resistance", "family communication"],
  },
  {
    slug: "legal-documents-caregivers-need",
    title: "Legal Documents Every Family Caregiver Needs to Have Ready",
    excerpt: "Power of attorney, healthcare proxy, POLST — a plain-language guide to the legal documents that protect your loved one and simplify care decisions.",
    category: "Caregiver Support",
    cluster: "caregiver",
    hub: "caregiver-support",
    publishDate: "2025-03-15",
    readTime: "9 min",
    isPillar: false,
    tags: ["power of attorney", "healthcare proxy", "legal documents", "caregiver"],
  },

  // CHRONIC DISEASE CLUSTER
  {
    slug: "managing-diabetes-at-home",
    title: "Managing Diabetes at Home: A Guide for Patients and Caregivers",
    excerpt: "Blood sugar monitoring, insulin management, wound care, and diet — how home health care supports diabetes management at home.",
    category: "Chronic Conditions",
    cluster: "chronic-disease",
    hub: "chronic-conditions",
    publishDate: "2025-03-22",
    readTime: "8 min",
    isPillar: false,
    tags: ["diabetes", "blood sugar", "insulin", "home health", "diabetic wounds"],
  },
  {
    slug: "copd-care-at-home",
    title: "COPD Care at Home: How to Breathe Easier and Stay Out of the Hospital",
    excerpt: "Practical tips for managing COPD at home — and how skilled nursing care prevents the flare-ups that lead to hospitalization.",
    category: "Chronic Conditions",
    cluster: "chronic-disease",
    hub: "chronic-conditions",
    publishDate: "2025-03-29",
    readTime: "7 min",
    isPillar: false,
    tags: ["COPD", "breathing", "chronic lung disease", "home health", "readmission prevention"],
  },
  {
    slug: "heart-failure-care-tips",
    title: "Heart Failure at Home: What Patients and Caregivers Need to Know",
    excerpt: "Daily weight monitoring, fluid restrictions, medication timing — a practical guide to managing congestive heart failure at home.",
    category: "Chronic Conditions",
    cluster: "chronic-disease",
    hub: "chronic-conditions",
    publishDate: "2025-04-05",
    readTime: "8 min",
    isPillar: false,
    tags: ["heart failure", "CHF", "cardiac care", "home health", "fluid monitoring"],
  },
  {
    slug: "stroke-rehabilitation-at-home",
    title: "Stroke Rehabilitation at Home: What to Expect and How to Help",
    excerpt: "How home-based stroke rehab works — the role of physical, occupational, and speech therapy in recovery, and how families can support progress.",
    category: "Home Recovery",
    cluster: "chronic-disease",
    hub: "home-recovery",
    publishDate: "2025-04-12",
    readTime: "9 min",
    isPillar: false,
    tags: ["stroke", "stroke recovery", "rehabilitation", "home therapy"],
  },
  {
    slug: "arthritis-pain-management",
    title: "Arthritis Pain Management at Home: What Actually Works",
    excerpt: "Evidence-based strategies for managing arthritis pain at home — from physical therapy and exercise to assistive devices and joint protection.",
    category: "Chronic Conditions",
    cluster: "chronic-disease",
    hub: "chronic-conditions",
    publishDate: "2025-04-19",
    readTime: "7 min",
    isPillar: false,
    tags: ["arthritis", "pain management", "joint protection", "occupational therapy"],
  },
  {
    slug: "parkinsons-home-care",
    title: "Parkinson's Disease Home Care: A Guide for Patients and Families",
    excerpt: "Managing Parkinson's at home — tremors, balance, speech, swallowing, and the role of home health therapy and nursing in maintaining quality of life.",
    category: "Chronic Conditions",
    cluster: "chronic-disease",
    hub: "chronic-conditions",
    publishDate: "2025-04-26",
    readTime: "9 min",
    isPillar: false,
    tags: ["Parkinson's disease", "home care", "speech therapy", "physical therapy", "caregiver"],
  },

  // HOME SAFETY CLUSTER
  {
    slug: "fall-prevention-for-seniors",
    title: "Fall Prevention for Seniors: A Room-by-Room Home Safety Guide",
    excerpt: "Falls are the leading cause of injury in older adults. Here's how to assess and modify every room in the home to dramatically reduce fall risk.",
    category: "Home Safety",
    cluster: "home-safety",
    hub: "home-safety",
    publishDate: "2025-03-28",
    readTime: "8 min",
    isPillar: false,
    tags: ["fall prevention", "home safety", "seniors", "bathroom safety", "Chicago"],
  },
  {
    slug: "how-to-make-home-safe-for-elderly",
    title: "How to Make Your Home Safe for an Elderly Parent",
    excerpt: "A comprehensive home safety checklist for families preparing to bring an aging parent home — or keep them safely in their current home.",
    category: "Home Safety",
    cluster: "home-safety",
    hub: "home-safety",
    publishDate: "2025-04-04",
    readTime: "8 min",
    isPillar: false,
    tags: ["home safety", "elderly", "home modification", "aging in place"],
  },
  {
    slug: "bathroom-safety-for-seniors",
    title: "Bathroom Safety for Seniors: The Essential Modifications",
    excerpt: "The bathroom is the most dangerous room in the home for older adults. Here are the modifications that matter most.",
    category: "Home Safety",
    cluster: "home-safety",
    hub: "home-safety",
    publishDate: "2025-04-11",
    readTime: "6 min",
    isPillar: false,
    tags: ["bathroom safety", "grab bars", "fall prevention", "seniors"],
  },
  {
    slug: "bedroom-safety-for-seniors",
    title: "Bedroom Safety for Seniors: Preventing Nighttime Falls",
    excerpt: "Most nighttime falls happen in or near the bedroom. Here's how to make sleeping and nighttime routines safer for older adults.",
    category: "Home Safety",
    cluster: "home-safety",
    hub: "home-safety",
    publishDate: "2025-04-18",
    readTime: "6 min",
    isPillar: false,
    tags: ["bedroom safety", "nighttime falls", "seniors", "home safety"],
  },
  {
    slug: "preventing-hospital-readmission",
    title: "10 Things That Prevent Hospital Readmission After Discharge",
    excerpt: "Evidence-based strategies to prevent returning to the hospital after discharge — and how professional home health care addresses all of them.",
    category: "Home Recovery",
    cluster: "home-safety",
    hub: "home-recovery",
    publishDate: "2025-04-25",
    readTime: "7 min",
    isPillar: false,
    tags: ["readmission prevention", "hospital discharge", "home health care"],
  },

  // POST-HOSPITAL CLUSTER
  {
    slug: "what-to-expect-after-hospital-discharge",
    title: "What to Expect After a Hospital Discharge (And How to Avoid Going Back)",
    excerpt: "The first 30 days after discharge are the highest-risk period for complications. Here's what families need to know — and do — to make it a success.",
    category: "Home Recovery",
    cluster: "post-hospital",
    hub: "home-recovery",
    publishDate: "2025-03-06",
    readTime: "7 min",
    isPillar: false,
    tags: ["hospital discharge", "home recovery", "post-hospital care", "readmission"],
  },
  {
    slug: "how-home-health-helps-recovery",
    title: "How Home Health Care Accelerates Recovery After Hospitalization",
    excerpt: "Research shows that home health care after discharge leads to faster recovery, fewer complications, and significantly lower readmission rates.",
    category: "Home Recovery",
    cluster: "post-hospital",
    hub: "home-recovery",
    publishDate: "2025-03-13",
    readTime: "6 min",
    isPillar: false,
    tags: ["home health", "recovery", "hospitalization", "outcomes"],
  },
  {
    slug: "post-surgery-recovery-timeline",
    title: "Post-Surgery Recovery Timeline: What to Expect Week by Week",
    excerpt: "A realistic look at recovery milestones after major surgery — and how home health care supports each phase of healing.",
    category: "Home Recovery",
    cluster: "post-hospital",
    hub: "home-recovery",
    publishDate: "2025-03-20",
    readTime: "8 min",
    isPillar: false,
    tags: ["surgery recovery", "recovery timeline", "post-surgical care", "home health"],
  },
  {
    slug: "physical-therapy-after-surgery",
    title: "Physical Therapy After Surgery: Why It Matters and What to Expect",
    excerpt: "Physical therapy is one of the most important parts of post-surgical recovery. Here's what home PT looks like and why starting early matters.",
    category: "Home Recovery",
    cluster: "post-hospital",
    hub: "home-recovery",
    publishDate: "2025-03-27",
    readTime: "7 min",
    isPillar: false,
    tags: ["physical therapy", "post-surgery", "rehabilitation", "home PT"],
  },
  {
    slug: "nutrition-for-healing",
    title: "Nutrition for Healing: What to Eat After Surgery or Illness",
    excerpt: "What patients eat after surgery or illness significantly affects recovery speed and outcomes. A clinically-grounded guide to healing nutrition.",
    category: "Home Recovery",
    cluster: "post-hospital",
    hub: "home-recovery",
    publishDate: "2025-04-03",
    readTime: "7 min",
    isPillar: false,
    tags: ["nutrition", "healing", "recovery diet", "post-surgery nutrition"],
  },
];

// Helper functions for blog
export function getArticlesByHub(hubSlug: string) {
  return allArticles.filter((a) => a.hub === hubSlug);
}

export function getArticlesByCluster(cluster: string) {
  return allArticles.filter((a) => a.cluster === cluster);
}

export function getPillarArticles() {
  return allArticles.filter((a) => a.isPillar);
}

export function getRelatedArticles(currentSlug: string, cluster: string, limit = 3) {
  return allArticles
    .filter((a) => a.slug !== currentSlug && a.cluster === cluster)
    .slice(0, limit);
}

export const blogClusters = [
  { id: "skilled-nursing", name: "Skilled Nursing", hub: "senior-health" },
  { id: "caregiver", name: "Caregiver Support", hub: "caregiver-support" },
  { id: "chronic-disease", name: "Chronic Conditions", hub: "chronic-conditions" },
  { id: "home-safety", name: "Home Safety", hub: "home-safety" },
  { id: "post-hospital", name: "Home Recovery", hub: "home-recovery" },
];
